#!/usr/bin/env bash
# Auto-generated by recreate_env_from_snapshot.sh for env: photomaker_NS
export PHOTOMAKER_PATH="/home/niko/.cache/huggingface/hub/models--TencentARC--PhotoMaker-V2/snapshots/f5a1e5155dc02166253fa7e29d13519f5ba22eac/photomaker-v2.bin"
export PM_PATH="/home/niko/.cache/huggingface/hub/models--TencentARC--PhotoMaker-V2/snapshots/f5a1e5155dc02166253fa7e29d13519f5ba22eac/photomaker-v2.bin"
