#!/usr/bin/env bash
# Auto-generated by recreate_env_from_snapshot.sh for env: photomaker_NS
# Populate NVIDIA pip CUDA runtime lib dirs (site-packages/nvidia/*/lib) if present.
if command -v python >/dev/null 2>&1; then
  _nvidia_pip_libs="$(python - <<'PY'
import glob
import os
import site

paths = []
for base in site.getsitepackages():
    for p in glob.glob(os.path.join(base, "nvidia", "*", "lib")):
        if os.path.isdir(p):
            paths.append(p)
seen = set()
ordered = []
for p in paths:
    if p not in seen:
        seen.add(p)
        ordered.append(p)
print(":".join(ordered))
PY
)"
  if [[ -n "${_nvidia_pip_libs}" ]]; then
    export NVIDIA_PIP_LIBS="${_nvidia_pip_libs}"
  fi
fi

if [[ -n "${NVIDIA_PIP_LIBS:-}" ]]; then
  export LD_LIBRARY_PATH="/home/niko/rsrch/diffusion_template/setup/env_snapshot_photomaker_NS/_gcc_runtime/lib:${NVIDIA_PIP_LIBS}:${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
else
  export LD_LIBRARY_PATH="/home/niko/rsrch/diffusion_template/setup/env_snapshot_photomaker_NS/_gcc_runtime/lib:${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
fi
export LD_PRELOAD="/home/niko/rsrch/diffusion_template/setup/env_snapshot_photomaker_NS/_gcc_runtime/lib/libstdc++.so.6:${LD_PRELOAD:-}"
