base_model_name: SG161222/RealVisXL_V4.0
saved_run_dir: saved/rhca_1e-4_ml_step2_allsteps_3Apr

branched_attn_weight_mode: noise_and_ref
branched_attn_new_weight_kind: lora
train_branched_ca_lora: true
ba_patch_top_k: 1.0
ba_train_top_k: 1.0
non_ba_train: false

disable_branched_sa: false
disable_branched_ca: false
strict_face_routing: false

mask_expansion_ratio: 1.0
mask_softness: 0.0

photomaker_start_step: 10
merge_start_step: 10
branched_attn_start_step: 15
branched_attn_end_step: null
num_inference_steps: 50
guidance_scale: 5
num_images_per_prompt: 1
val_debug: false

face_embed_strategy: id
train_branch_mode: both
branched_start_mode: both
pose_adapt_ratio: 0.0
ca_mixing_for_face: false
photomaker_use_lora_adapter: false

use_branched_attention: true
auto_mask_ref: false
use_dynamic_mask: false
use_bbox_mask_ref: true
use_bbox_mask_gen: true

saved_checkpoint: ${saved_run_dir}/checkpoint-epoch5.pth
bbox_mask_gen_path: ${saved_run_dir}/one_id_ref_bboxes_auto.json
bbox_mask_gen_fallback_path: ../dataset_full/one_id/one_id_ref_bboxes.json
cometml_id: null
output_dir: outputs/infer/rhca_1e-4_ml_step2_allsteps_3Apr
batch_size: 1

writer:
  _target_: src.logger.cometml.CometMLWriter
  project_name: "rsrch_30Oct"
  workspace: null
  run_name: "rhca_1e-4_ml_step2_allsteps_3Apr_infer"
  mode: "online"
  loss_names: ["loss"]
  log_checkpoints: false
  id_length: 32

model:
  _target_: src.model.photomaker_branched.lora2.PhotomakerBranchedLora
  pretrained_model_name_or_path: ${base_model_name}
  photomaker_path: ${oc.env:HOME}/.cache/huggingface/hub/models--TencentARC--PhotoMaker-V2/snapshots/f5a1e5155dc02166253fa7e29d13519f5ba22eac/photomaker-v2.bin
  weight_dtype: bf16
  target_size: 1024
  rank: 32
  photomaker_lora_rank: 64
  lora_modules: [to_q, to_k, to_v, to_out.0]
  init_lora_weights: gaussian
  trigger_word: img
  id_alpha: 0.3
  use_attn_v2: false
  use_id_embeds: false
  pose_adapt_ratio: ${pose_adapt_ratio}
  ca_mixing_for_face: ${ca_mixing_for_face}
  face_embed_strategy: ${face_embed_strategy}
  train_branch_mode: ${train_branch_mode}
  branched_attn_weight_mode: ${branched_attn_weight_mode}
  branched_attn_new_weight_kind: ${branched_attn_new_weight_kind}
  train_branched_ca_lora: ${train_branched_ca_lora}
  train_ba_only: true
  ba_train_top_k: ${ba_train_top_k}
  ba_patch_top_k: ${ba_patch_top_k}
  non_ba_train: ${non_ba_train}
  photomaker_start_step: ${photomaker_start_step}
  merge_start_step: ${merge_start_step}
  branched_attn_start_step: ${branched_attn_start_step}
  num_inference_steps: ${num_inference_steps}

pipeline:
  _target_: src.pipelines.photomaker_branched_clean.PhotomakerBranchedPipeline.from_pretrained
  pretrained_model_name_or_path: ${base_model_name}
  torch_dtype: bfloat16
  use_safetensors: true
  variant: null
  photomaker_start_step: ${photomaker_start_step}
  photomaker_use_lora_adapter: ${photomaker_use_lora_adapter}
  merge_start_step: ${merge_start_step}
  branched_attn_start_step: ${branched_attn_start_step}
  branched_attn_end_step: ${branched_attn_end_step}
  branched_start_mode: ${branched_start_mode}
  train_branch_mode: ${train_branch_mode}
  pose_adapt_ratio: ${pose_adapt_ratio}
  ca_mixing_for_face: ${ca_mixing_for_face}
  face_embed_strategy: ${face_embed_strategy}
  auto_mask_ref: ${auto_mask_ref}
  use_dynamic_mask: ${use_dynamic_mask}
  use_bbox_mask_ref: ${use_bbox_mask_ref}
  use_bbox_mask_gen: ${use_bbox_mask_gen}

dataset:
  _target_: src.datasets.manual_val.ManualPhotoMakerValDataset
  images_dir: ../dataset_full/one_id/ref
  prompts_path: ../dataset_full/val_dataset/prompts_10.txt
  classes_json_path: ../dataset_full/one_id/one_id_classes_ref.json
  bbox_mask_ref: ../dataset_full/one_id/nm0005092_adj_test.json
  bbox_mask_gen: ${bbox_mask_gen_fallback_path}
  seeds: [0]
  limit: 12

validation_args:
  negative_prompt: "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, signature, watermark, blurry"
  debug_dir: hm_debug
  val_debug: ${val_debug}
  num_images_per_prompt: ${num_images_per_prompt}
  num_inference_steps: ${num_inference_steps}
  guidance_scale: ${guidance_scale}
  height: 1024
  width: 1024
  target_size: [1024, 1024]
  original_size: [1024, 1024]
  crops_coords_top_left: [0, 0]
  use_branched_attention: ${use_branched_attention}
  face_embed_strategy: ${face_embed_strategy}
  photomaker_start_step: ${photomaker_start_step}
  photomaker_use_lora_adapter: ${photomaker_use_lora_adapter}
  merge_start_step: ${merge_start_step}
  branched_attn_start_step: ${branched_attn_start_step}
  branched_attn_end_step: ${branched_attn_end_step}
  mask_expansion_ratio: ${mask_expansion_ratio}
  mask_softness: ${mask_softness}
  branched_start_mode: ${branched_start_mode}
  auto_mask_ref: ${auto_mask_ref}
  use_dynamic_mask: ${use_dynamic_mask}
  use_bbox_mask_ref: ${use_bbox_mask_ref}
  use_bbox_mask_gen: ${use_bbox_mask_gen}
