train:
    dreambooth:
        _target_: src.datasets.dreambooth.DreamBoothTrainDataset
        data_path: /home/jovyan/bobkov/dreambooth/dataset/dog
        placeholder_token: sks
        class_name: dog
        instance_transforms: ${transforms.instance_transforms.train}
      
    # cosmic:
    #     _target_: src.datasets.cosmic.CosmicDoubledTrain
    #     cosmic_json_pth: /home/jovyan/bobkov/persongen/cosmic_gathered.json
    #     cosmic_texts_json_pth: /home/jovyan/bobkov/all_texts_cosmic_by_qween3.json 
    #     cosmic_large_json_pth: /home/jovyan/bobkov/cosmic_large_alldata.json
    #     cosmic_large_texts_json_pth: /home/jovyan/bobkov/all_texts_cosmic_large_by_qween3_trigger_word.json
    #     images_path: /home/jovyan/bobkov/cosmic_data
    #     num_refs: 1
    #     instance_transforms: ${transforms.instance_transforms.train}

    cosmic:
        _target_: src.datasets.cosmic.CosmicDoubledTrain
        cosmic_json_pth: ../dataset_full/cosmic_gathered.json
        cosmic_texts_json_pth: ../dataset_full/all_texts_cosmic_by_qween3.json 
        cosmic_large_json_pth: ../dataset_full/cosmic_large_alldata.json
        cosmic_large_texts_json_pth: ../dataset_full/all_texts_cosmic_large_by_qween3_trigger_word.json
        images_path: /home/aalanov/Bobkov_Denis/datasets/CosmicManHQ-1.0/
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}

    one_id:
        _target_: src.datasets.cosmic.OneIDTrain
        cosmic_json_pth: ../dataset_full/one_id/nm0005092_adj_train.json
        images_path: ../dataset_full/one_id/nm0005092_adj
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        instance_transforms: ${transforms.instance_transforms.train}

    large_dataset:
        _target_: src.datasets.cosmic.LargeDatasetTrain
        data_json_pth: ../dataset_full/filtered_ids3_adj.json
        images_path: ../dataset_full/large_dataset_adj/large_dataset
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}
  
    large_dataset_serv:
        _target_: src.datasets.cosmic.LargeDatasetTrain
        data_json_pth: /mnt/virtual_ai0001053-01309_SR006-nfs1/nasilaev/datasets/dataset_full/filtered_ids3_adj.json
        images_path: /mnt/virtual_ai0001053-01309_SR006-nfs1/nasilaev/datasets/dataset_full/large_dataset_adj/large_dataset
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}
  

    cosmic_large:
        _target_: src.datasets.cosmic.CosmicLargeTrain
        data_json_pth: /mnt/virtual_ai0001053-01309_SR006-nfs1/bobkov/cosmic_data/gathered_data_cosmic_large_filtered.json
        images_path: /mnt/virtual_ai0001053-01309_SR006-nfs1/bobkov/cosmic_data/LAION-5B-Filtered-Large-Faces/laion1B-nolang
        path_prefix_to_strip: LAION-5B-Filtered-Large/laion1B-nolang
        require_nested_identity_subdir: true
        upscale_to_1024: ${train_dataset_upscale_to_1024}
        const_ref: ${train_dataset_const_ref}
        crop_ref: ${train_dataset_crop_ref}
        ref_similar: ${train_dataset_ref_similar}
        origtarget_genref: ${train_dataset_origtarget_genref}
        crop_nonface_min: ${train_dataset_crop_nonface_min}
        crop_nonface_max: ${train_dataset_crop_nonface_max}
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}

    cosmic_large_local:
        _target_: src.datasets.cosmic.CosmicLargeTrain
        data_json_pth: /home/kolyangg/rsrch/dataset_full/cosmic_large/gathered_data_cosmic_large_filtered_sample_two.json
        images_path: /home/kolyangg/rsrch/dataset_full/cosmic_large/LAION-5B-Filtered-Large-Faces
        target_images_path: /home/kolyangg/rsrch/dataset_full/LAION-5B-Filtered-Large
        path_prefix_to_strip: LAION-5B-Filtered-Large
        num_refs: 1
        instance_transforms: ${transforms.instance_transforms.train}

    cosmic_large_vast:
        _target_: src.datasets.cosmic.CosmicLargeTrain
        data_json_pth: /workspace/datasets/gathered_data_cosmic_large_filtered.json
        images_path: /workspace/datasets/LAION-5B-Filtered-Large-Faces/laion1B-nolang
        path_prefix_to_strip: LAION-5B-Filtered-Large/laion1B-nolang
        require_nested_identity_subdir: true
        upscale_to_1024: ${train_dataset_upscale_to_1024}
        const_ref: ${train_dataset_const_ref}
        crop_ref: ${train_dataset_crop_ref}
        ref_similar: ${train_dataset_ref_similar}
        origtarget_genref: ${train_dataset_origtarget_genref}
        crop_nonface_min: ${train_dataset_crop_nonface_min}
        crop_nonface_max: ${train_dataset_crop_nonface_max}
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}

    cosmic_large_clust:
        _target_: src.datasets.cosmic.CosmicLargeTrain
        data_json_pth: ../../datasets/gathered_data_cosmic_large_filtered.json
        images_path: ../../datasets/LAION-5B-Filtered-Large-Faces/laion1B-nolang
        target_images_path: /home/aalanov/Bobkov_Denis/datasets/CosmicManHQ-1.0/LAION-5B-Filtered-Large/laion1B-nolang
        path_prefix_to_strip: LAION-5B-Filtered-Large/laion1B-nolang
        require_nested_identity_subdir: true
        upscale_to_1024: ${train_dataset_upscale_to_1024}
        const_ref: ${train_dataset_const_ref}
        crop_ref: ${train_dataset_crop_ref}
        ref_similar: ${train_dataset_ref_similar}
        origtarget_genref: ${train_dataset_origtarget_genref}
        crop_nonface_min: ${train_dataset_crop_nonface_min}
        crop_nonface_max: ${train_dataset_crop_nonface_max}
        num_refs: 1
        train_on_separate_image: ${train_on_separate_image}
        same_id_ref_map_json_pth: null
        instance_transforms: ${transforms.instance_transforms.train}

val:
    db_liv_small:
      _target_: src.datasets.dreambooth.DreamBoothLivingSmall
      data_path: /home/jovyan/bobkov/dreambooth/dataset/dog
      placeholder_token: sks
      class_name: dog

    # man:
    #   _target_: src.datasets.man_datasets.ManValDataset
    #   data_json_pth: /home/jovyan/bobkov/persongen/filtered_ids3.json
    #   images_path: /home/jovyan/bobkov/full_dataset
    
    man_face:
      _target_: src.datasets.man_datasets.ManValFaceDataset
      data_json_pth: /home/jovyan/bobkov/persongen/filtered_ids3.json
      images_path: /home/jovyan/bobkov/full_dataset

    man:
      _target_: src.datasets.cosmic.CosmicDoubledTrain
      cosmic_json_pth: ../dataset_full/cosmic_gathered.json
      cosmic_texts_json_pth: ../dataset_full/all_texts_cosmic_by_qween3.json
      cosmic_large_json_pth: ../dataset_full/cosmic_large_alldata.json
      cosmic_large_texts_json_pth: ../dataset_full/all_texts_cosmic_large_by_qween3_trigger_word.json
      images_path: /home/aalanov/Bobkov_Denis/datasets/CosmicManHQ-1.0/
      num_refs: 1
      instance_transforms: ${transforms.instance_transforms.train}
      limit: 3

    manual_val:
      _target_: src.datasets.manual_val.ManualPhotoMakerValDataset
      images_dir: ../dataset_full/val_dataset/references
      prompts_path: ../dataset_full/val_dataset/prompts_10.txt
      classes_json_path: ../dataset_full/val_dataset/classes_ref.json
      bbox_mask_ref: ../dataset_full/val_dataset/ref_bboxes.json
      # bbox_mask_gen: ../dataset_full/val_dataset/pm96_bboxes.json
      bbox_mask_gen: ../dataset_full/val_dataset/pm96_bboxes_new.json
      seeds: [0] # [0, 1, 2]
      limit: 96 # 20
      # limit: 4 # temp

    manual_val_two:
      _target_: src.datasets.manual_val.ManualPhotoMakerValDataset
      images_dir: ../dataset_full/val_dataset/references_two
      prompts_path: ../dataset_full/val_dataset/prompts_10.txt
      classes_json_path: ../dataset_full/val_dataset/classes_ref.json
      bbox_mask_ref: ../dataset_full/val_dataset/ref_bboxes.json
      bbox_mask_gen: ../dataset_full/val_dataset/pm96_bboxes_new.json
      seeds: [0]
      limit: 20

    one_id_val:
      _target_: src.datasets.manual_val.ManualPhotoMakerValDataset
      images_dir: ../dataset_full/one_id/ref
      prompts_path: ../dataset_full/val_dataset/prompts_10.txt
      classes_json_path: ../dataset_full/one_id/one_id_classes_ref.json
      bbox_mask_ref: ../dataset_full/one_id/nm0005092_adj_test.json
      bbox_mask_gen: ../dataset_full/one_id/one_id_ref_bboxes.json
      seeds: [0]
      # limit: 96 # 10 # 1
      limit: 12 # 10 # 1
  
