defaults:
  - trainer: sdxl
  - model: sdxl_lora
  - writer: console
  - transforms: only_instance
  - ddp: accelerate
  - lr_scheduler: constant
  - pipeline: sdxl
  - metrics: all_metrics
  - datasets: all_datasets
  - dataloaders: all_dataloaders
  - _self_

optimizer:
  _convert_: partial
  _target_: torch.optim.AdamW
  weight_decay: 0

loss_function:
  _target_: src.loss.diffusion_loss.DiffusionLoss

lr_for_unet: 1e-4

train_dataset_name: "dreambooth"
val_datasets_names: ["db_liv_small"]

inference_metrics: ["dino", "clip_ts"]

validation_args:
  negative_prompt: "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, signature, watermark, blurry"
  num_images_per_prompt: 5
  num_inference_steps: 50
  guidance_scale: 5
  height: 1024
  width: 1024
  target_size: [1024, 1024]
  original_size: [1024, 1024]
  crops_coords_top_left: [0, 0]


