defaults:
  - trainer: photomaker_lora
  - model: photomaker_branched_lora
  - writer: console
  - transforms: only_instance
  - ddp: accelerate
  - lr_scheduler: custom_linear
  - pipeline: photomaker_branched
  - metrics: all_metrics
  - datasets: all_datasets
  # - datasets: all_datasets_local
  - dataloaders: all_dataloaders
  - _self_

# Resume/continuation controls
continue_run: true
# saved_checkpoint: saved/pm2_br_bbox/checkpoint-epoch2.pth   # absolute or relative path to *.pth
saved_checkpoint: checkpoint-epoch5.pth   # absolute or relative path to *.pth
saved_config: saved/pm2_br_bbox/config.yaml       # optional path to saved config.yaml (not required)
cometml_id: tbzl6icmyop6wq2dd7bs5bdl2sj9yg05         # CometML experiment key to resume logging

ddp_timeout_seconds: 21600  # 6 hours to cover long validations

optimizer:
  _convert_: partial
  _target_: torch.optim.AdamW
  weight_decay: 0

loss_function:
  _target_: src.loss.diffusion_loss.MaskedDiffusionLoss

lr_for_lora: 1e-5

train_dataset_name: "cosmic"
val_datasets_names: ["manual_val"]

inference_metrics: ["clip_ts", "id_sim_best"]

validation_debug_timing: false

validation_args:
  negative_prompt: "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, signature, watermark, blurry"
  debug_dir: hm_debug_orig
  num_images_per_prompt: 5
  num_inference_steps: 50
  guidance_scale: 5
  height: 1024
  width: 1024
  target_size: [1024, 1024]
  original_size: [1024, 1024]
  crops_coords_top_left: [0, 0]
  use_branched_attention: true
  face_embed_strategy: ${pipeline.face_embed_strategy}
  photomaker_start_step: ${pipeline.photomaker_start_step}
  merge_start_step: ${pipeline.merge_start_step}
  branched_attn_start_step: ${pipeline.branched_attn_start_step}
  branched_start_mode: ${pipeline.branched_start_mode}
