train:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  grad_accum_enabled: false
  batch_size_eff: null
  num_workers: 1
  pin_memory: false

manual_val:
  _target_: torch.utils.data.DataLoader
  batch_size: 1
  num_workers: 1
  pin_memory: false
